#+title: Letter to an Unborn Son

Sep 3 2003
I'm not sure how to start this, I guess. I'm just hoping that I'll figure it out as I go. I love you. I'm your father, and I meant to write you this letter before you were born, but I couldn't figure out what to say. I wanted to tell you how to figure life out, how to be great, to be happy ... cause it's hard. That's not what they told me when I was little. I thought it'd be a lot easier, but this is what it is, and it can still be the most beautiful thing that's ever happened to you, but you have to work to figure it out for yourself. I have to own it. No one else can be responsible for your life other than yourself. You have to trust me on this. You have everything you need to figure it out, but you may never see it yourself. You don't see what is real. You see what you fear. Most of the time.

Be curious and learn as much as you can, especially about what we know about ourselves. Learn humans and never stop trying to be a stonger person. Stronger as in more intelligent and wiser, not more tolerant to pain. Don't run from pain. Learn from it. Learn to focus sharply in the middle of it. Make informed decisions in the heat of the moment by using whatever you can (patience, meditation, practice, love, compassion) to see the moment for what it is and don't let it consume you. Practice. Learm from our strongest traditions from all corners of the earth.


Sep 13 2023
Resist the temptation to demonize. We are have within us the capacity for tremendous good and profound evil. Likewise, resist the temptation to annoint. Trust yourself, and carefully navigate what is an enormously complex reality.
